### ISSUE TITLE
package not available for R version 3.1.2

### ISSUE THREAD

**Issue by TrofimovAssya** [bhklab/genefu#10]
Hi!

I am trying to install _genefu_ and it doesn't seem to work for the new version of R 3.2.2.
I tried on another machine as well, with R running 3.1.2.
I also tried installing from url:
`> install.packages(url="http://bioconductor.org/packages/genefu/", 'genefu')
Warning in install.packages :
  package ‘genefu’ is not available (for R version 3.1.2)`

Thanks in advance!

**Comment by bhaibeka** [comment]
can you try the following?

```
source("https://bioconductor.org/biocLite.R")
biocLite("genefu")
```

**Comment by TrofimovAssya** [comment]
Hi!
It doesnt work!


> source("https://bioconductor.org/biocLite.R")
Error in file(filename, "r", encoding = encoding) :
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) : unsupported URL scheme

**Comment by TrofimovAssya** [comment]
Update:
For R 3.2.2, it doesn't support https, so the non-secure one worked:

> source("http://bioconductor.org/biocLite.R")

However, when I do 

> biocLite("genefu")
it gives me the following error for the lava package dependency.

`Error: file ‘/var/folders/y0/f_41pv_13kj5j6nj_dh8w2h80000gp/T//RtmpByxAH0/downloaded_packages/lava_1.4.1.tgz’ is not an OS X binary package
In addition: Warning messages:
1: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 32832 != reported length 1036121
2: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 24104 != reported length 282678
3: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 33724 != reported length 790087
4: 'tar' returned non-zero exit code 1 `

Can the package run without?

**Comment by bhaibeka** [comment]
We do not use lava, but it could be a dependency of one of our dependencies. Try to install it from source: https://cran.r-project.org/web/packages/lava/index.html

**Comment by TrofimovAssya** [comment]
Update:
In order for everything to install and load, I have done the following steps:
- install _lava_ from source
- install _prodlim_ from source
- re-install _Rcpp_ and update the file
- re-install _genefu_

The package loaded with warnings about dependency versions.
Will close issue when I test the package.

Thanks for the support!
