### ISSUE TITLE
Using genefu with other tumor than breast cancer

### ISSUE THREAD

**Issue by demis001** [bhklab/genefu#11]
@bhklab

I am new to the concept of the classification, I am doing some sort of tutorial with other solid tumor different from breast cancer. Would you please guid me how to proceed?

1. I have my own subtype signature with 3 subtype of about 500 genes
2. I have a gene expression of 20000 genes with 700 samples

The current status: 
`clast<-intrinsic.cluster(data=data, annot=annot, do.mapping=TRUE, std="robust", intrinsicg=intr, number.custer=3,mins=3, method.cor="spearman", method.centroids="mean", verbos=TRUE)`
# 489/500 probes are used in clustering 
Note: 

`dim(data)`
 ` #700   20000`
 `dim(annot)`
  `#20000  3`
 `dim(intr)`
  `# 500  3`

I got "clast" object  as a list,  but  I don't know how to assign the cluster to my signature list with three subtypes. I don't know how this signature generated but I have to use the 500 genes and 3 subtypes to subtype the 700 samples.

`names(clast)`
`# "model"   "subtype"  "subtype.proba"  "cor" `

"subtype"  and "subtype.proba" have names as cluster.1, cluster.2 and cluster.3

How should I  associate the 3 subtype names in my signature gene list with the above cluster?

Note: the signature subtyper is a matrix of the following format
...
               ,Subtype1,subtype2,subtype 3
Gene1,2.000,-1.000 , 0.000
Gene500,3.000, 2.000,0.7222
...
Thank you for your guidance!

Sorry it is my first time to try it

**Comment by bhaibeka** [comment]
I do not understand your question. The function is performing a model-based clustering ao all the genes are used to determine the three clusters. You can always do a manual differential gene expression to rank the genes based on their discriminatory power for each specific subtype

**Comment by ChristopherEeles** [comment]
If this issue persists, please reopen it using the most recent version of genefu.

Best,
Christopher Eeles
Software Developer
BHK Lab | PM-Research | UHN
