### ISSUE TITLE
Potential mapping issue

### ISSUE THREAD

**Issue by bhaibeka** [bhklab/genefu#13]
https://www.biostars.org/p/313540/

**Comment by danielnewhouse** [comment]
I have gone through the demo data analysis found in the manual with no problems. Using my RNAseq data, I was able to get PAM50 subtyping to run successfully, but am now running into issues with Claudin Low.

From the demo data, it looks like I should be able to use the same data and annotation input I used for PAM50, but I am receiving the following error:

SubtypePredictions<-molecular.subtyping(sbt.model = "claudinLow",data = dataCL, annot = annotCL, do.mapping = TRUE)
Error in data1[, gg.uniq, drop = FALSE] : subscript out of bounds

**Comment by bhaibeka** [comment]
Make sure annot rownames are not numbers (make it for instance "geneid.12345") and run the updated claudinLow function
