### ISSUE TITLE
question about samples treatment conditions when using molecular.subtyping

### ISSUE THREAD

**Issue by jiajiayb** [bhklab/genefu#16]
Hi, hope this message finds you well. I found this tool super helpful, I can run the code successfully which I am very happy about. But I have a question about the proper way to use this tool. The RNA-Seq samples I am testing coming from breast cancer patients that are either treatment naive or after having chemo/radio therapies. My question is that for this subtyping tool, does it have any requirement on patients' treatment condition? one more question is that if this tool only worked on primary tumor, or can also work on metastatic tumor? Many thanks to your time and help.

**Comment by avkitex** [comment]
I'm working a lot with transcriptomics classifications. 
It's a kind of fundamental question. The PAM50 classification is based on receptors, proliferation genes and structural genes (cytokeratines). If the applied treatment changes expression of proliferation genes (all CDK inhibitors and receptor inhibitors also do that) - than the observed PAM50 class will be different from the baseline. For example: LUMB is more proliferative than LUMA or Basal-like subtype looks like Normal-like, but with high proliferation genes expression. With any centroid-based classifiers you definitely will catch this. 
Check the PAM50 genes heatmap (TCGA) 
![image](https://user-images.githubusercontent.com/9219423/66746165-1abe0a80-ee4f-11e9-9113-e988b8183ad3.png)
Legend 
![image](https://user-images.githubusercontent.com/9219423/66746304-696ba480-ee4f-11e9-82e8-6bd92ad5f911.png)

**Comment by bhaibeka** [comment]
This is an excellent question that has not been thoroughly investigated in te literature, mainly due to the lack of samples at the time. @avkitex 's answer makes sense and I suspect the non-PAM50 classifiers will  behave similarly (at least the SCM classifiers). 

If you want to carry out a comprehensive study on subtyping of post-treatment and metastatic transcriptomes, I would be interested to review it.

**Comment by jiajiayb** [comment]
@avkitex Thank you very much for your response. That was exactly my concern. As you pointed out, on-treatment samples may have different expression profiles than baseline samples. The samples I am analyzing were undergone chemo- or radio-therapy when the biopsies were taken. Also, some samples are treatment naive. So it is really a mixture of baseline and on-treatment samples. Since chemo or radiotherapy are not targeted therapies, do you have any suggestions on predicting these samples' PAM50 subtypes using genefu? Any caveats? many thanks.

**Comment by jiajiayb** [comment]
@bhaibeka  I did not find any literature specifically address these questions and thank you for the confirmation that I did not miss anything. At this moment I can only run successfully PAM50 subtype classifier and hit the wall when tried other methods. I will open another issue for the specific question I met when using other classifiers. Many thanks :)

**Comment by avkitex** [comment]
@bhaibeka @jiajiayb
BTW ER+%, and all other groups % will also affect the classification. 
Check the data set GSE93204. There are post-anastrazole and palbociclib samples there. You will see clear switch to less proliferation subtype post treatment

**Comment by bhaibeka** [comment]
"BTW ER+%, and all other groups % will also affect the classification." True for most classifiers but not AIMS in theory

**Comment by avkitex** [comment]
Agreed.
We've developed a similar approach to be applied for the same types of issues (Grade classification, ABC/GCB, response prediction...) with quite promising results
