### ISSUE TITLE
endoPredict, gene70, gene76 and possible oncotypedx functions don't appear to work

### ISSUE THREAD

**Issue by BairdMcI** [bhklab/genefu#17]
Hi there,

This is my first ever Issue submission for a github project, so please bear with me.

I am trying to run the functions I have listed above (endoPredict, gene70, gene76 and oncotypedx, and they were all producing NULL information, or in some cases, exactly the same risk / score using my data. When I tried to run the example script (usually something along the lines of 
rs.vdxs <- _function_(data=data.vdxs,_ annot=annot.vdxs, do.mapping=TRUE), either with or without the mapping, I also just got NULL results back, leading me to believe that there might be something off about the functions?

Running the latest version of R (4.0.3) and Genefu (2.22.0).

Any help would be much appreciated, thanks!

**Comment by ChristopherEeles** [comment]
Hi @BairdMcI,

Thanks for reporting the issue. I will investigate and get back to you shortly.

Best,
Christopher Eeles
Software Developer
Benjamin Haibe-Kains Lab
Princess Margaret Cancer Center

**Comment by ChristopherEeles** [comment]
Hi @BairdMcI,

I ran the functions you listed using the example data in the package and everything seems to be working correctly. I am guessing the issues are related to your specific data set.

If the data set is public are you able to share a subset of it with me? For example, you can output the code necessary to generate and R object using the `dput` function. If you can post the first 10 rows of your data as strings I can run the functions on it and determine what is going wrong.

For the NULL results, all of the functions you specified use the `complete.cases` function to exclude rows with missing values. Is it possible that your data has at least one missing value in the gene expression data for each row? That would result in a return of NULL. If this is the case I recommend using the `impute` package to impute your missing values before running the functions.

Regarding returning the same risks/scores for your data as the example data, I would need some data to replicate the issue before I can tell you what is going on.

If you can also post the return from `sessionInfo()` that will give me more details about your R environment so I can rule that out as a cause.

Best,
Christopher Eeles

**Comment by BairdMcI** [comment]
> Hi @BairdMcI,
> 
> I ran the functions you listed using the example data in the package and everything seems to be working correctly. I am guessing the issues are related to your specific data set.
> 
> If the data set is public are you able to share a subset of it with me? For example, you can output the code necessary to generate and R object using the `dput` function. If you can post the first 10 rows of your data as strings I can run the functions on it and determine what is going wrong.
> 
> For the NULL results, all of the functions you specified use the `complete.cases` function to exclude rows with missing values. Is it possible that your data has at least one missing value in the gene expression data for each row? That would result in a return of NULL. If this is the case I recommend using the `impute` package to impute your missing values before running the functions.
> 
> Regarding returning the same risks/scores for your data as the example data, I would need some data to replicate the issue before I can tell you what is going on.
> 
> If you can also post the return from `sessionInfo()` that will give me more details about your R environment so I can rule that out as a cause.
> 
> Best,
> Christopher Eeles

Thank you for the reply.
Here is the first 10 lines of the data:

  | GSM1680327_136_rep1-TE | GSM1680351_190_rep1-TE | GSM1680280_027_rep1-TE | GSM1680300_063_rep1-TE | GSM1680380_278_rep1-TE | GSM1680319_113_rep1-TE | GSM1680399_351_rep1-TE | GSM1680384_281_rep1-TE | GSM1680268_022_rep1-TE | GSM1680303_065_rep1-TE | GSM1680312_076_rep1-TE | GSM1680408_508_rep1-TE | GSM1680263_012_rep1-TE | GSM1680271_024_rep1-TE | GSM1680284_031_rep1-TE | GSM1680367_238_rep1-TE | GSM1680336_146_rep1-TE
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
55879 | 1.347687 | 1.244134 | 1.173558 | 0.907664 | 1.147678 | 0.954021 | 1.049592 | 1.333946 | 0.859381 | 0.72587 | 1.169055 | 1.041796 | 1.206826 | 0.955181 | 1.15759 | 1.091803 | 1.143044
10106 | 2.904939 | 2.228413 | 3.225185 | 2.909665 | 4.81729 | 2.562242 | 1.570679 | 3.604294 | 5.528964 | 2.353584 | 5.1831 | 4.409306 | 2.278246 | 3.430912 | 1.737388 | 5.21425 | 3.058546
9911 | 0.207138 | 0.317091 | 0.249685 | 0.198099 | 0.21115 | 0.346963 | 0.303821 | 0.246577 | 0.443413 | 0.315904 | 0.245078 | 0.240912 | 0.197564 | 0.240017 | 0.325501 | 0.269081 | 0.222984
54898 | 1.484953 | 1.487427 | 1.404352 | 1.49261 | 2.241443 | 1.431082 | 1.825079 | 1.310952 | 1.173698 | 1.381884 | 1.285872 | 1.040998 | 1.483103 | 1.150676 | 1.782087 | 1.419939 | 1.336979
84174 | 1.117418 | 1.380975 | 1.073658 | 0.975652 | 1.159952 | 1.109714 | 1.180773 | 1.029156 | 1.05716 | 1.156867 | 1.005801 | 1.048978 | 1.053451 | 0.926453 | 1.131746 | 1.076254 | 1.03427
9110 | 0.925115 | 1.015816 | 0.906169 | 0.955341 | 0.892548 | 0.926594 | 0.804068 | 0.890092 | 0.941884 | 0.85556 | 0.95478 | 0.936875 | 0.909058 | 0.861115 | 0.899434 | 0.860781 | 0.899005
54039 | 2.227532 | 1.247814 | 1.390693 | 1.31337 | 1.585707 | 1.507881 | 1.308508 | 1.597233 | 1.738924 | 1.631711 | 1.992134 | 1.542691 | 1.482463 | 1.369145 | 1.723365 | 1.682709 | 1.455306
27338 | 0.323098 | 1.429221 | 0.369239 | 0.460004 | 1.012278 | 0.463487 | 0.486319 | 0.380575 | 0.34392 | 0.446514 | 0.623357 | 0.604514 | 0.795684 | 0.428174 | 0.918815 | 0.314722 | 0.45568
267012 | 0.966342 | 1.509638 | 1.522692 | 1.329394 | 1.094661 | 1.28033 | 1.604894 | 1.060637 | 1.15823 | 1.0365 | 1.254066 | 1.076331 | 1.310741 | 0.920109 | 1.116229 | 1.179887 | 0.997664
6189 | 0.286068 | 0.237584 | 0.166147 | 0.116293 | 0.100546 | 0.066882 | 0.17555 | 0.212943 | 0.263079 | 0.217 | 0.16108 | 0.044283 | 0.058823 | 0.171213 | 0.057234 | 0.172431 | 0.076311

I've checked the data, and there are no missing values (as defined by NAs or Infs; used `anyNA()` and `is.infinite()` to check). I've written together a small script, as I suspect the problem is in the annotation stage, since I'm not 100% sure if what I'm doing is correct. The first part of script is dealing with the fact that the data I have originally uses HGNC symbols, so I convert this to ENTREZGENE_ID first, since this seems to be what the documentation suggests. After that, I do this to attempt to run Endopredict, in this case
`annot = data.frame(probe=row.names(data.IDC.expression.subset), Gene.Symbol=row.names(data.IDC.expression.subset))
row.names(annot) <- annot$Gene.Symbol

randomSamples = sample(c(1:100), 17)
data.endo.input = data.frame(matrix(ncol=17, nrow=nrow(data.IDC.expression.subset)))
colnames(data.endo.input) = colnames(data.IDC.expression.subset)
rownames(data.endo.input) = rownames(data.IDC.expression.subset)
for (i in 1:ncol(data.IDC.expression)){
  data.endo.input[, i] = data.IDC.expression.subset[, i, randomSamples[i]]
}`

The output I get from this is the usual score, risk etc, but all the scores are 15, and all the risks are 1, which seems unlikely, especially as I have run it through the rorS function and it was very different.

SessionInfo(), excluding the "loaded via a namespace" packages:
`R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] TCGAbiolinks_2.18.0    ISOpureR_1.1.3         viridis_0.5.1          viridisLite_0.3.0      ggplot2_3.3.3          genefu_2.22.0          AIMS_1.22.0           
 [8] Biobase_2.50.0         BiocGenerics_0.36.0    e1071_1.7-4            iC10_1.5               iC10TrainingData_1.3.1 impute_1.64.0          pamr_1.56.1           
[15] cluster_2.1.0          biomaRt_2.46.0         limma_3.46.0           mclust_5.4.7           survcomp_1.40.0        prodlim_2019.11.13     survival_3.2-7  `

Thanks for your time!

**Comment by ChristopherEeles** [comment]
Hi @BairdMcI,

I cannot load a markdown table into R. Could you please run:
`dput(head(data.endo.input))`
and 
`dput(heat(annot))`

Then paste the returned strings here. This allows me to copy and paste the objects into R and debug the function.

Best,
Chris

**Comment by BairdMcI** [comment]
> Hi @BairdMcI,
> 
> I cannot load a markdown table into R. Could you please run:
> `dput(head(data.endo.input))`
> and
> `dput(head(annot))`
> 
> Then paste the returned strings here. This allows me to copy and paste the objects into R and debug the function.
> 
> Best,
> Chris

Hi there,
Sorry about that, here you go:
data.endo.input:
`structure(list(`GSM1680327_136_rep1-TE` = c(1.34768677596648, 
2.90493902174835, 0.207138234163693, 1.48495282579428, 1.11741757761666, 
0.925114627003646), `GSM1680351_190_rep1-TE` = c(1.24413427600834, 
2.22841320473751, 0.317090642819561, 1.48742738609645, 1.38097537091751, 
1.0158160683208), `GSM1680280_027_rep1-TE` = c(1.1735581423458, 
3.22518545288965, 0.249685467618546, 1.40435228070653, 1.07365818271764, 
0.906168747326541), `GSM1680300_063_rep1-TE` = c(0.907664174204858, 
2.90966504008782, 0.198098712653212, 1.49261019982785, 0.975652434428012, 
0.955341300213804), `GSM1680380_278_rep1-TE` = c(1.14767764791778, 
4.81728964791398, 0.211149608045978, 2.24144332021826, 1.15995210774489, 
0.892547765766769), `GSM1680319_113_rep1-TE` = c(0.95402115313066, 
2.56224217307933, 0.346963354088332, 1.43108229773183, 1.10971394826873, 
0.926594381769045), `GSM1680399_351_rep1-TE` = c(1.04959157158036, 
1.57067912317086, 0.303820579453108, 1.82507870454844, 1.18077347659951, 
0.804068100130875), `GSM1680384_281_rep1-TE` = c(1.33394621077542, 
3.60429391548109, 0.246576783392666, 1.31095219113573, 1.02915622369445, 
0.890092363018862), `GSM1680268_022_rep1-TE` = c(0.859380627032112, 
5.5289636240656, 0.443413426317256, 1.17369829162424, 1.05716027585107, 
0.941884223738488), `GSM1680303_065_rep1-TE` = c(0.725869710003711, 
2.35358438485583, 0.315904098573867, 1.38188375467081, 1.15686714949911, 
0.855560166720956), `GSM1680312_076_rep1-TE` = c(1.16905513347301, 
5.18310018470189, 0.24507781173861, 1.28587166208819, 1.00580085854161, 
0.954779727748588), `GSM1680408_508_rep1-TE` = c(1.04179555015622, 
4.40930578130915, 0.24091164562671, 1.04099805997195, 1.04897823929763, 
0.93687472844164), `GSM1680263_012_rep1-TE` = c(1.20682596359335, 
2.27824578760413, 0.197563645472304, 1.48310292291983, 1.05345090470955, 
0.909058422335594), `GSM1680271_024_rep1-TE` = c(0.95518069239292, 
3.43091170877758, 0.240017183299011, 1.15067617084829, 0.92645338935715, 
0.861115092918131), `GSM1680284_031_rep1-TE` = c(1.15758993582795, 
1.73738787362, 0.325500939536172, 1.78208721303481, 1.13174637275636, 
0.899433825480308), `GSM1680367_238_rep1-TE` = c(1.09180284382671, 
5.2142502337848, 0.269081192114035, 1.41993873084261, 1.07625449270119, 
0.860780917195504), `GSM1680336_146_rep1-TE` = c(1.14304433406411, 
3.05854550768547, 0.222983583347503, 1.33697929422375, 1.03427038522373, 
0.899004601389406)), row.names = c("55879", "10106", "9911", 
"54898", "84174", "9110"), class = "data.frame")`

Annot:
`structure(list(probe = c("55879", "10106", "9911", "54898", "84174", 
"9110"), Gene.Symbol = c("55879", "10106", "9911", "54898", "84174", 
"9110")), row.names = c("55879", "10106", "9911", "54898", "84174", 
"9110"), class = "data.frame")`

I should also add that I'm running endoPredict itself using:
`endoPredict(data=t(as.matrix(data.endo.input)), annot=annot, mapping=T)`

Thanks for your time

**Comment by ChristopherEeles** [comment]
Hi @BairdMcI,

Thanks for the data, I was able to load it and test the functions. So it seems there are two issues:

Firstly, if you need to `do.mapping` then one column in the annotation data.frame must be named 'EntrezGene.ID', otherwise the mapping won't work (see `?endoPredict`). If I do this with the data you shared, however, it does not resolve the issue.

Secondly, when I step through the `endoPredict` function it appears there is no overlap between the genes you provided and the genes in the respective signature. I checked this for `gene70` and it is also the case there. Without any gene mappings, the function is not able to make predictions and therefore returns NA for all samples. If you set `verbose=TRUE` in the function, it shows a message letting you know what has gone wrong.

If you do not specify `do.mapping=TRUE`, there is a bug in the function which causes all samples to be assigned the value of -2.63, which predicts poor prognosis for all samples and thus a 1 for prediction and a 15 for score. I will correct this bug and push the changes later this week; look for genefu=2.22.1 to be available from Bioconductor.

To work around the issues for now, you can look at the genes in the signature for each of the prediction functions. This can be achieved by calling `data(sig.<function_name>)`, e.g. `data(sig.endoPredict)` will load the gene signature object used in the endoPredict function. You then need to make sure that one or more of the 'EntrezGene.ID' values match the 'EntrezGene.ID' value in the signature, otherwise no predictions can be made and the results will be NA for all samples.

Let me know if I can do anything else to assist you. I will leave this issue open until I am able to push the bug fix to Bioconductor.

Best,
Chris

**Comment by BairdMcI** [comment]
> Hi @BairdMcI,
> 
> Thanks for the data, I was able to load it and test the functions. So it seems there are two issues:
> 
> Firstly, if you need to `do.mapping` then one column in the annotation data.frame must be named 'EntrezGene.ID', otherwise the mapping won't work (see `?endoPredict`). If I do this with the data you shared, however, it does not resolve the issue.
> 
> Secondly, when I step through the `endoPredict` function it appears there is no overlap between the genes you provided and the genes in the respective signature. I checked this for `gene70` and it is also the case there. Without any gene mappings, the function is not able to make predictions and therefore returns NA for all samples. If you set `verbose=TRUE` in the function, it shows a message letting you know what has gone wrong.
> 
> If you do not specify `do.mapping=TRUE`, there is a bug in the function which causes all samples to be assigned the value of -2.63, which predicts poor prognosis for all samples and thus a 1 for prediction and a 15 for score. I will correct this bug and push the changes later this week; look for genefu=2.22.1 to be available from Bioconductor.
> 
> To work around the issues for now, you can look at the genes in the signature for each of the prediction functions. This can be achieved by calling `data(sig.<function_name>)`, e.g. `data(sig.endoPredict)` will load the gene signature object used in the endoPredict function. You then need to make sure that one or more of the 'EntrezGene.ID' values match the 'EntrezGene.ID' value in the signature, otherwise no predictions can be made and the results will be NA for all samples.
> 
> Let me know if I can do anything else to assist you. I will leave this issue open until I am able to push the bug fix to Bioconductor.
> 
> Best,
> Chris

Thanks for the reply and the info. I will have a play around with the data and see if there is a problem with the conversion from HGNC to Entrez, and if that is causing the Entrez gene IDs to not be found or anything like that.

If I was to do `do.mapping=TRUE`, but still not have any overlap between the gene signatures (if my looking at the raw data fails), would this still be a reliable indicator or not really, since the function isn't using the specific genes to make the predictions?

Thanks for your time and help,
Baird

**Comment by ChristopherEeles** [comment]
Hi @BairdMcI,

I am not the original package author, but as far as I can tell from the code and documentation if no genes in your data are in the respective gene signature then no predictions can be made at all. In this case the function should return all NAs.

It seems that when `do.mapping=TRUE`, there is an additional constraint that ALL of the EntrezGene.IDs in your annotation data.frame have to be in the signature otherwise all NAs are returned.

This constraint is not present what 'do.mapping=FALSE`, so if you can rename all of the genes in your data to EntrezGene.ID (i.e., the colnames of the input data are EntrezGene.IDs) then predictions will be made with a partial signature. In this case the predictions would be meaningful and should not be NA unless there is no overlap between the colnames of the input data and the EntrezGene.IDs of the gene signature object.

Best,
Chris

**Comment by BairdMcI** [comment]
Ok, great to know, thank you very much

**Comment by BairdMcI** [comment]
Good afternoon,

I've had a look through the data, and have confirmed that my annotation and data does have the gene signatures used in endoPredict (just not in the head of the annot, which is what I sent you above). As you say however, when using `do.mapping=FALSE`, all the numbers come up as 1 or 15, indicating the bug you were talking about. If I run it with `do.mapping=T`, I get the error `Error in data1[, gg.uniq, drop = FALSE] : subscript out of bounds`. I'm not sure what that is about.

Thank you for your time

**Comment by BairdMcI** [comment]
What I'm also noticing, is that for the gene70 and gene76 algorithms, the gene signatures required include around 15 genes each, which do not have known EntrezGene.IDs, such as some of the contigs and probes, so I'm not sure how one can ever pull together data that has a full set of the genes that the algorithms use. It's also perhaps worth noting that in the gene70 and gene76 signatures, although the EntrezGene.ID, NCBI.gene.symbol etc are "NA" for some of the probes, a quick google or check of annotations reveal they do actually have an EntrezGeneID, so I can substitute that in.

Hopefully that made some sense!
Thanks for your time,
Baird

**Comment by BairdMcI** [comment]
> Good afternoon,
> 
> I've had a look through the data, and have confirmed that my annotation and data does have the gene signatures used in endoPredict (just not in the head of the annot, which is what I sent you above). As you say however, when using `do.mapping=FALSE`, all the numbers come up as 1 or 15, indicating the bug you were talking about. If I run it with `do.mapping=T`, I get the error `Error in data1[, gg.uniq, drop = FALSE] : subscript out of bounds`. I'm not sure what that is about.
> 
> Thank you for your time

Ok, I've just realised that I was quite wrong with this. My annotation dataframe was incorrectly labelled (as you had pointed out above, and I had forgotten to change the code for), so I am at least getting different numbers out now, when using `do.mapping=T`. 
I think my point still stands about the gene70 and gene76 algorithms requiring EntrezGene.IDs which are not obtainable, due to the genes used by the original algorithms, but I'm not really sure if that's a genefu issue or not.

Thank you for your help, and apologies for leading you around in circles!
Baird

**Comment by ChristopherEeles** [comment]
Hi @BairdMcI,

The updates to genefu (2.22.1) are now available in Bioc 3.12. They should prevent the bug we discussed and also add some more useful error and warning messages. I am closing this issue now. Please feel free to open another one if you require further assistance.

Best,
Chris
