### ISSUE TITLE
Subtyping mouse samples

### ISSUE THREAD

**Issue by maringa780** [bhklab/genefu#21]
Hello,

I'm trying to subtype (PAM50) mouse breast cancer samples (RNAseq) and I was wondering if Genefu accounts for the fact that the genes in mouse have different gene id compared to their human orthologs. Please advice. 
Thanks.

**Comment by ChristopherEeles** [comment]
Hi @maringa780, 

As far as I know our gene signatures would all use human based gene ids. If I remember correctly, we use gene symbols.

The simplest solution would be to map the mouse gene symbols to human gene symbols before using the classifier.

Best,
Christopher Eeles
Software Developer
Benjamin Haibe-Kains Lab
PM-Research | University Health Network

**Comment by ChristopherEeles** [comment]
Hi @maringa780,

Just read through some of the documentation. The type of gene identifier depends on the classifier used. Some use gene symbol and some use Entrez gene id.

For more information please see `?molecular.subtyping` in the R console. That will bring up documentation explaining the requirements for using the function.

Best,
Chirs
