### ISSUE TITLE
About claudinLow function to analyze three groups of patients

### ISSUE THREAD

**Issue by HengqiLiu** [bhklab/genefu#23]
Hi "genefu" package team:

I have three groups of patients and plan to perform `claudinLow` analysis on them, but I find that such an error will be reported: 
`Error in dimnames(x) <- dn : length of 'dimnames' [2] not equal to array extent.`

When I use only two groups of patients, it works perfectly. 

I found that the error is caused by these two lines of code of the `claudinLow` function
       
`colnames(distances) <- c("euclidian distance to Claudin-low", "euclidian distance to Others")`

What I want to know is if there is a way to perform `claudinLow` analysis on the three groups of patients.

Thank you !!

**Comment by ChristopherEeles** [comment]
Hi @HengqiLiu,

To help resolve your issue I need three pieces of information.

Firstly, please run the `sessionInfo()` function in your R console and provide the output here. This will give me the necessary background information about your R environment, such as which version of packages you are using.

Secondly, I need the exact code you are trying to execute to see which function options you are using.

Finally, I need a small subset of your input data to use for debugging. You can use the `dput` function return the code needed to make an R object. Please provide the input matrix you are using, as well as any additional data that you may be passing into the function. You are retrieve this information like this:
```
dput(head(x))
```

Where x is your input to the `claudinLow` function. Then copy and paste the value and post it here.

Once I have this information I can try running your code and see what is going wrong.

Best,
Christopher Eeles
Software Developer
BHK Lab | PM-Research | UHN

**Comment by HengqiLiu** [comment]
Hi Christopher Eeles: 

Thank you for your prompt reply, and I apologize to you because my own data input mistake caused the error. I used my own patient group information as a train dataset insted of the `claudinLowData` dataset. After I corrected my mistake, the `claudinLow` function can run perfectly and output the result. 

Thank you and your team for developing genefu tools.

Best,
Henqi Liu
