### ISSUE TITLE
How to use an in-house-dataset to evaluate centroids for PAM50 method

### ISSUE THREAD

**Issue by marcellosalvi** [bhklab/genefu#24]
Dear developer,
I was looking for a method to use my own dataset to evalute centroids for intrinsic.cluster.predict function.
I managed to evaluate my own centroids using intrinsic.cluster but then I was not able to recapitulate the five different subtype ( THe clusters has as name cluster.1 cluster.2 cluster.3 ecc).
Is it possible to fix this problem?

**Comment by ChristopherEeles** [comment]
Hi @marcellosalvi,

Please provide the code you are trying to run, your expected output, as well as the actual output you receive. It is also helpful if you share your `sessionInfo()` so I can see which version of R and the genefu package you are using.

Best,
Christopher Eeles
Software Developer
BHK Lab | PM-Research | UHN

**Comment by ChristopherEeles** [comment]
Hi @marcellosalvi,

The `instrinsic.cluster` function is for training a new classification model based on a gene list. If you want to classify your samples based on one of the included classifiers in `genefu` you should use the `instrinsic.cluster.predict` method.

For example, if you want to use the `pam50` model to make sub-type predictions on your new data, you could do something like:
```{r}
data(pam50.robust)  # load the robust model
intrinsic.subtype.predict(sbt.model=pam50.robust, data=log2cpm, annot=annot.log2cpm)
```
Where `annot.log2cpm` is a table mapping from the feature names in your data to Entrez gene id. See `?intrinsic.subtype.predict` in the R console for the full documentation.

It is also worth noting that it appears you are trying to classify RNA sequencing data with `genefu`. The package was designed for use with RNA microarray data, and the included centroids may not generalize to RNA sequencing data. Please see issue #22 for more details on the challenges of applying `genefu` to RNA seq data.

Best,
Chris

**Comment by ChristopherEeles** [comment]
Hi @marcellosalvi,

I am closing this issue now. If you have more questions feel free to re-open it.

Best,
Chris
