### ISSUE TITLE
Different results when subtyping with AIMS within genefu and using AIMS package

### ISSUE THREAD

**Issue by jakalssj3** [bhklab/genefu#25]
Hello. I ran AIMS classification using the genefu package. To cross-check my results I did the same using the AIMS package. The conclusion is that the results differ. I get different subtypes assigned to the same samples, and also the probability scores are much lower when using genefu. Why is this happening? Note, I have used exactly the same gene expression data for both packages.

**Comment by bhaibeka** [comment]
That is weird. This could be due to different annotation (genefu uses EntrezGene ID). Can you post your code and adat to let us reproduce the results?
