### ISSUE TITLE
Can this package be applied to RNA-seq data?

### ISSUE THREAD

**Issue by lincj1994** [bhklab/genefu#26]
Hi.
Can this package be applied to RNAseq Data, such as the ontypedx and gene70 functions? OR only Affymetrix data is allowed?

**Comment by ChristopherEeles** [comment]
Hi @lincj1994,

The gene signatures in this package were all derived from expression micro-arrays. While the functions will work for RNA-seq data, the validity of the results are a matter which requires applying your scientific judgment.

See #22 for a more detailed discussion.

Best,
Christopher Eeles
Software Developer
BHK Lab | PM-Research | UHN
