### ISSUE TITLE
PAM50 classification

### ISSUE THREAD

**Issue by elicabe** [bhklab/genefu#30]
Hello,

I am using your package genefu for PAM50 classification of tumors. I have observed that the samples analyzed with HGU133A does not contain 6 of the 50 genes of PAM50. ANLN, CDC20, NUF2, CXXC5, GPR160, KNTC2AP and PHGDH. You used in your example case 2 databases that were analyzed with HGU133A (GSE11121 and GSE7390) and you give a PAM50 classification of the samples. I would like to know how do you perform it? Did you check before that the result is the same with or without these 6 genes? Do you have some bibliography support for this decision?

Thank you very much for your help inn advance.

Best regards

**Comment by elicabe** [comment]
Thank you very much for your email. I still have one more question, in you
paper "A Three-Gene Model to Robustly Identify Breast Cancer Molecular
Subtypes", you use 36 gene expression datasets and a lot of them are
analyzed with HGU113A and Agilent that do not contain the 50 genes of
PAM50. How do you perform the PAM50 classification that appears in the
paper? Did you assume in this case that PAM50 without all the genes
generates the same result as PAM50 with the 50 genes?

Thank you very much for your help in advance and sorry for all the
questions.

Best
Marina

**Comment by ChristopherEeles** [comment]
Hi @elicabe,

When some of the genes in the signature are missing from a sample we simply compute the distance to each subtypes centroid using the genes which are present. The assigned subtype is the one with the smallest distance to your sample.

As such, the package provides a best approximation of which subtype your sample belongs to. It does not, however, confirm that the subtype is correct. For example, if you provide samples from another cancer type the classifier will still assign the closest breast cancer subtype. This is why @bhaibeka suggested use additional cluster validation and stability quantification methods to make sure the assignment makes sense for your specific data set, assay and normalization method.

You must exercise your scientific judgement when determining if the assigned subtypes are correct enough to be useful in your analysis.

Best,
Christopher Eeles
Software Developer
Haibe-Kains Lab
