### ISSUE TITLE
Problem with subtype and crisp classification with AIMS

### ISSUE THREAD

**Issue by detorrentel** [bhklab/genefu#9]
As I understand it what you call the subtype.crisp should be a binary matrix with 1 in the subtype where the sample is classified and 0 otherwise. If you run your example:

```
data(vdxs)
sbt.vdxs.AIMS <- molecular.subtyping(sbt.model="AIMS",data=data.vdxs, annot=annot.vdxs,do.mapping=FALSE)
```

You can see that some samples are classified differently in `sbt.vdxs.AIMS$subtype` and `sbt.vdxs.AIMS$subtype.crisp`. For example, VDX_78 is classified as HER2 but in the crisp matrix it has a 1 in LumA (other problems are VDX_93, VDX_612, VDX_9 etc.). I went through your raw script (molecular.subtyping.R) and I think the problem is when you build the probability matrix. You do it by row but actually it should be by column.
Instead of (line 126 in molecular.subtyping.R):

```
sbts$subtype.proba <- matrix(unlist(sbts$all.probs$`20`), ncol = 5, byrow = TRUE)
```

it should be

```
sbts$subtype.proba <- matrix(unlist(sbts$all.probs$`20`), ncol = 5)
```

I tried to run it like that and I have the impression that it’s working.
Best,
Laurence

**Comment by ChristopherEeles** [comment]
If this issue persists, please reopen it using the most recent version of `genefu`.

Best,
Christopher Eeles
Software Developer
BHK Lab | PM-Research | UHN
